### ISSUE TITLE
Clear lag mod creating phantom blocks

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AdultCraft-Foundations#22]
The clear lag mod is creating phantom blocks. If you keep going when it says waiting for server, it turns those blocks into phantom blocks, some are experiencing rubber-banding.

**Comment by ResqDiver1317** [comment]
Not an issue with ClearLag specifically. This is due to the lag spike that is occurring. "Ghost Blocks" are "created" by a desync between the client and server. Once the pregen finishes, clearlag should have an easier time with it's process as right now, it's still trying to check non generated chunks so that is adding to the issue causing them to get out of sync.

**Comment by ResqDiver1317** [comment]
Pretty sure this was a Lag issue that is resolved now.
